[workspace]
members = [
  "./crates/structmapper",
  "./crates/structmapper-test",
  "./crates/structmapper-codegen"
]

[patch.crates-io]
structmapper-codegen = { path = "./crates/structmapper-codegen" }
